### ISSUE TITLE
group_dir generation

### ISSUE THREAD

**Issue by cuihaojie-plus** [fanq15/GCoNet#11]
Hi~

  Can you explain the rule for generating group_dir？

Best wishes!

**Comment by fanq15** [comment]
Hi, Thanks for your interests to our work.
This group_dir is to repeat the experiments of our final model.
We found that the results highly rely on the group sequences.
Thus we record the group sequences during training.
This repo is only for the results reimplementation.
If you want to build your own model, please refer to our new code repo of GCoNet+, which is more stable and robust to the group sequences.

**Comment by cuihaojie-plus** [comment]
Got it. Many thanks~
