### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by ldkong1205** [fanq15/GCoNet#2]
Hi Qi. Good work. Will you release the training code of GCoNet and its training dataset mentioned in the paper? Are the models mentioned in Table 2 of the paper using the same training dataset before evaluations? Thanks.

**Comment by fanq15** [comment]
Hi, I use the code of GICD. I need to get their permission before releasing the training code.
I will release the training code asap.

**Comment by fanq15** [comment]
Some models use different training dataset, e.g. MS COCO.

**Comment by ldkong1205** [comment]
> Hi, I use the code of GICD. I need to get their permission before releasing the training code.
> I will release the training code asap.

Got it. 👍

**Comment by ldkong1205** [comment]
> Some models use different training dataset, e.g. MS COCO.

OK. By the way, since this information is omitted in the paper, could you share it in this repository when you are convenient?

**Comment by fanq15** [comment]
Code is released.
