### ISSUE TITLE
Code Excludes Training Part

### ISSUE THREAD

**Issue by a-arnold66** [fanq15/GCoNet#3]
Just wondering. 

Why don't you open-source the whole project with both training and testing code and make it reproducible? 

Simply uploading checkpoints and the so-called saliency maps are not "open-source" at all.

A formal open source project should contain complete and reproducible code and parameter settings for readers to verify.

**Comment by fanq15** [comment]
Hi, I use the code of GICD. I need to get their permission before releasing the training code.
I will release the training code asap.

**Comment by fanq15** [comment]
Code is released.
