### ISSUE TITLE
result not well

### ISSUE THREAD

**Issue by mozpp** [fanq15/GCoNet#5]
![image](https://user-images.githubusercontent.com/25809906/115979749-52684f80-a5ba-11eb-8bfa-0ae6e6096301.png)

**Comment by mozpp** [comment]
![image](https://user-images.githubusercontent.com/25809906/115979867-ff42cc80-a5ba-11eb-8c7d-f121e1883ec8.png)

**Comment by a-arnold66** [comment]
The scores are not very high (on CoCA and CoSOD3k), too.

It makes sense because this task is relatively new and more challenging compare to saliency detection.

But I don't think the comparison in their paper is reasonable. First, the models they listed are not trained/tested on the same data set. Also, I believe some of them are using different backbones.

Hope the authors can clarify this.

**Comment by fanq15** [comment]
Hi, these images are from CoCA dataset.
It is a very challenging dataset whose images contain very complex environments and non-target objects.
From the quantitative results on CoCA, you can also see that current methods perform worse on this dataset, especially compared to Cosal2015.
I think these results are acceptable for the challenging CoCA dataset and these artifacts give us clues for the future research direction on CoSOD.
We just take a small step towards the challenging real-world CoSOD.

**Comment by fanq15** [comment]
@a-arnold66 Hi, we use the same backbone (VGGNet) and training dataset (DUST dataset) as GICD. The CoSOD datasets are valuable and therefore are only used for evaluation.

**Comment by mozpp** [comment]
> Hi, these images are from CoCA dataset.
> It is a very challenging dataset whose images contain very complex environments and non-target objects.
> From the quantitative results on CoCA, you can also see that current methods perform worse on this dataset, especially compared to Cosal2015.
> I think these results are acceptable for the challenging CoCA dataset and these artifacts give us clues for the future research direction on CoSOD.
> We just take a small step towards the challenging real-world CoSOD.

CoCA 看来是比较难，同一类图，类内差距比较大。
我现实生活采一些难度第一点的数据测一下，看一下gconet行不行
